// Route: /reward-queue
// Operational queue for admin/manager staff to review, approve, reject,
// mark-redeemed, or cancel every ReferralReward generated by the Referral
// Reward Redemption System, across all members.
import React, { useCallback, useEffect, useState } from 'react';
import {
  rewardService,
  type ReferralReward,
  type RewardStats,
  type RewardStatus,
  type RewardType,
} from '../utils/supabase/reward-service';
import { Card, CardContent, CardHeader, CardTitle } from '../components/ui/card';
import { Badge } from '../components/ui/badge';
import { Button } from '../components/ui/button';
import { Input } from '../components/ui/input';
import { Label } from '../components/ui/label';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '../components/ui/select';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '../components/ui/table';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from '../components/ui/dialog';
import { Textarea } from '../components/ui/textarea';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from '../components/ui/dropdown-menu';
import {
  Gift,
  Clock,
  CheckCircle,
  XCircle,
  Ban,
  MoreHorizontal,
  ChevronLeft,
  ChevronRight,
  Search,
  RefreshCw,
  PackageCheck,
  Layers,
} from 'lucide-react';
import { toast } from 'sonner';

const STATUS_OPTIONS: RewardStatus[] = ['PENDING', 'AVAILABLE', 'CLAIMED', 'REDEEMED', 'EXPIRED', 'CANCELLED'];
const REWARD_TYPE_OPTIONS: RewardType[] = [
  'WALLET_CREDIT', 'MEMBERSHIP_EXTENSION', 'MEMBERSHIP_DISCOUNT', 'FREE_PT',
  'FREE_CLASS', 'COUPON', 'LOYALTY_POINTS', 'GIFT', 'CASH',
];

const REWARD_TYPE_LABELS: Record<RewardType, string> = {
  WALLET_CREDIT: 'Wallet Credit',
  MEMBERSHIP_EXTENSION: 'Membership Extension',
  MEMBERSHIP_DISCOUNT: 'Membership Discount',
  FREE_PT: 'Free PT',
  FREE_CLASS: 'Free Class',
  COUPON: 'Coupon',
  LOYALTY_POINTS: 'Loyalty Points',
  GIFT: 'Gift',
  CASH: 'Cash',
};

const STATUS_BADGE_CLASS: Record<RewardStatus, string> = {
  PENDING: 'bg-yellow-100 text-yellow-800',
  AVAILABLE: 'bg-blue-100 text-blue-800',
  CLAIMED: 'bg-purple-100 text-purple-800',
  REDEEMED: 'bg-green-100 text-green-800',
  EXPIRED: 'bg-gray-200 text-gray-700',
  CANCELLED: 'bg-red-100 text-red-800',
};

const PAGE_SIZE = 20;

type ActionType = 'approve' | 'reject' | 'cancel';

const ACTION_LABEL: Record<ActionType, string> = {
  approve: 'Approve',
  reject: 'Reject',
  cancel: 'Cancel',
};

function formatDate(value?: string): string {
  if (!value) return '—';
  const d = new Date(value);
  if (isNaN(d.getTime())) return '—';
  return d.toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' });
}

function isPastExpiry(reward: ReferralReward): boolean {
  if (!reward.expiryDate) return false;
  if (reward.status === 'EXPIRED' || reward.status === 'REDEEMED' || reward.status === 'CANCELLED') return false;
  return new Date(reward.expiryDate).getTime() < Date.now();
}

function formatRewardValue(reward: ReferralReward): string {
  if (reward.rewardValue === undefined || reward.rewardValue === null) return '—';
  switch (reward.rewardType) {
    case 'WALLET_CREDIT':
    case 'CASH':
      return `${reward.currency ? reward.currency + ' ' : ''}${reward.rewardValue}`;
    case 'MEMBERSHIP_EXTENSION':
      return `${reward.rewardValue} day${reward.rewardValue === 1 ? '' : 's'}`;
    default:
      return String(reward.rewardValue);
  }
}

function approvalDisplay(reward: ReferralReward): string {
  if (reward.approvedBy) return `Approved by ${reward.approvedBy}`;
  if (reward.approvalRequired) return 'Required';
  return '—';
}

export function RewardQueue() {
  const [rewards, setRewards] = useState<ReferralReward[]>([]);
  const [loading, setLoading] = useState(false);
  const [stats, setStats] = useState<RewardStats | null>(null);

  const [currentPage, setCurrentPage] = useState(1);
  const [totalPages, setTotalPages] = useState(1);
  const [totalItems, setTotalItems] = useState(0);

  const [statusFilter, setStatusFilter] = useState<string>('all');
  const [typeFilter, setTypeFilter] = useState<string>('all');
  // Branch and Membership filters from the original spec are intentionally
  // skipped — ReferralReward has no branch/membership-plan field yet.
  const [searchInput, setSearchInput] = useState('');
  const [search, setSearch] = useState('');

  const [actionDialog, setActionDialog] = useState<{ type: ActionType; reward: ReferralReward } | null>(null);
  const [remarks, setRemarks] = useState('');
  const [processing, setProcessing] = useState(false);

  // Debounce the free-text search before it hits the server-side filter.
  useEffect(() => {
    const t = setTimeout(() => setSearch(searchInput.trim()), 400);
    return () => clearTimeout(t);
  }, [searchInput]);

  // Any filter change resets pagination back to page 1.
  useEffect(() => {
    setCurrentPage(1);
  }, [statusFilter, typeFilter, search]);

  const loadRewards = useCallback(async () => {
    setLoading(true);
    try {
      const res = await rewardService.getRewards({
        page: currentPage,
        size: PAGE_SIZE,
        status: statusFilter !== 'all' ? statusFilter : undefined,
        rewardType: typeFilter !== 'all' ? typeFilter : undefined,
        search: search || undefined,
      });
      setRewards(res.rewards);
      setTotalPages(res.pagination.totalPages || 1);
      setTotalItems(res.pagination.totalItems || 0);
    } catch (err: any) {
      toast.error(err.message || 'Failed to load rewards');
    } finally {
      setLoading(false);
    }
  }, [currentPage, statusFilter, typeFilter, search]);

  useEffect(() => {
    loadRewards();
  }, [loadRewards]);

  const loadStats = useCallback(async () => {
    try {
      const s = await rewardService.getStats();
      setStats(s);
    } catch (err: any) {
      // Stats are a best-effort summary strip — don't block the queue on failure.
      toast.error(err.message || 'Failed to load reward stats');
    }
  }, []);

  useEffect(() => {
    loadStats();
  }, [loadStats]);

  const refreshAll = useCallback(async () => {
    await Promise.all([loadRewards(), loadStats()]);
  }, [loadRewards, loadStats]);

  const openAction = (type: ActionType, reward: ReferralReward) => {
    setActionDialog({ type, reward });
    setRemarks('');
  };

  const confirmAction = async () => {
    if (!actionDialog) return;
    const { type, reward } = actionDialog;
    setProcessing(true);
    try {
      if (type === 'approve') await rewardService.approve(reward.id, remarks || undefined);
      else if (type === 'reject') await rewardService.reject(reward.id, remarks || undefined);
      else if (type === 'cancel') await rewardService.cancel(reward.id, remarks || undefined);
      toast.success(`Reward ${reward.rewardCode} ${type === 'approve' ? 'approved' : type === 'reject' ? 'rejected' : 'cancelled'}`);
      setActionDialog(null);
      await refreshAll();
    } catch (err: any) {
      toast.error(err.message || `Failed to ${type} reward`);
    } finally {
      setProcessing(false);
    }
  };

  const handleMarkRedeemed = async (reward: ReferralReward) => {
    try {
      await rewardService.redeem(reward.id);
      toast.success(`Reward ${reward.rewardCode} marked as redeemed`);
      await refreshAll();
    } catch (err: any) {
      toast.error(err.message || 'Failed to mark reward redeemed');
    }
  };

  const cardShell = 'border-primary/10 shadow-md hover:shadow-lg transition-shadow';

  return (
    <div className="p-6 space-y-6">
      {/* Header */}
      <div className="flex justify-between items-start">
        <div>
          <h1 className="text-3xl font-bold">Reward Queue</h1>
          <p className="text-muted-foreground mt-2">
            Review, approve, and redeem every reward generated by the referral program
          </p>
        </div>
        <Button variant="outline" onClick={refreshAll}>
          <RefreshCw className="mr-2 h-4 w-4" />
          Refresh
        </Button>
      </div>

      {/* Key Metrics */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
        <Card className={cardShell}>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium text-primary">Total Generated</CardTitle>
            <div className="bg-gradient-light p-2 rounded-lg">
              <Layers className="h-4 w-4 text-primary" />
            </div>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-primary">{stats?.totalGenerated ?? 0}</div>
            <p className="text-xs text-muted-foreground">All rewards ever generated</p>
          </CardContent>
        </Card>

        <Card className={cardShell}>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium text-primary">Pending Approval</CardTitle>
            <div className="bg-yellow-50 p-2 rounded-lg">
              <Clock className="h-4 w-4 text-yellow-600" />
            </div>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-yellow-600">{stats?.pendingApproval ?? 0}</div>
            <p className="text-xs text-muted-foreground">Awaiting staff review</p>
          </CardContent>
        </Card>

        <Card className={cardShell}>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium text-primary">Redeemed</CardTitle>
            <div className="bg-green-50 p-2 rounded-lg">
              <CheckCircle className="h-4 w-4 text-green-600" />
            </div>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-green-600">{stats?.redeemed ?? 0}</div>
            <p className="text-xs text-muted-foreground">Fully claimed by members</p>
          </CardContent>
        </Card>

        <Card className={cardShell}>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium text-primary">Expired</CardTitle>
            <div className="bg-gray-100 p-2 rounded-lg">
              <XCircle className="h-4 w-4 text-gray-600" />
            </div>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-gray-600">{stats?.expired ?? 0}</div>
            <p className="text-xs text-muted-foreground">Lapsed before redemption</p>
          </CardContent>
        </Card>
      </div>

      {/* Filters */}
      <Card className={cardShell}>
        <CardContent className="p-4">
          <div className="flex flex-wrap gap-4 items-end">
            <div className="flex-1 min-w-[220px]">
              <Label htmlFor="reward-search">Search</Label>
              <div className="relative mt-1">
                <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                <Input
                  id="reward-search"
                  placeholder="Search by reward code, member ID, or reward name..."
                  value={searchInput}
                  onChange={(e) => setSearchInput(e.target.value)}
                  className="pl-10"
                />
              </div>
            </div>
            <div>
              <Label htmlFor="status-filter">Status</Label>
              <Select value={statusFilter} onValueChange={setStatusFilter}>
                <SelectTrigger id="status-filter" className="w-[170px] mt-1">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">All Statuses</SelectItem>
                  {STATUS_OPTIONS.map((s) => (
                    <SelectItem key={s} value={s}>{s.charAt(0) + s.slice(1).toLowerCase()}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div>
              <Label htmlFor="type-filter">Reward Type</Label>
              <Select value={typeFilter} onValueChange={setTypeFilter}>
                <SelectTrigger id="type-filter" className="w-[190px] mt-1">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">All Types</SelectItem>
                  {REWARD_TYPE_OPTIONS.map((t) => (
                    <SelectItem key={t} value={t}>{REWARD_TYPE_LABELS[t]}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Table */}
      <Card className={cardShell}>
        <CardContent className="p-0">
          <Table>
            <TableHeader className="bg-slate-50/50">
              <TableRow className="hover:bg-transparent">
                <TableHead>Reward Code</TableHead>
                <TableHead>Member</TableHead>
                <TableHead>Member Type</TableHead>
                <TableHead>Reward Rule</TableHead>
                <TableHead>Reward Type</TableHead>
                <TableHead>Reward Value</TableHead>
                <TableHead>Status</TableHead>
                <TableHead>Approval</TableHead>
                <TableHead>Expiry</TableHead>
                <TableHead>Generated Date</TableHead>
                <TableHead>Redeemed Date</TableHead>
                <TableHead className="text-right">Actions</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {loading && (
                <TableRow>
                  <TableCell colSpan={12} className="text-center py-8 text-muted-foreground">
                    Loading rewards...
                  </TableCell>
                </TableRow>
              )}
              {!loading && rewards.length === 0 && (
                <TableRow>
                  <TableCell colSpan={12} className="text-center py-8 text-muted-foreground">
                    <Gift className="h-8 w-8 mx-auto mb-2 opacity-40" />
                    No rewards match the current filters.
                  </TableCell>
                </TableRow>
              )}
              {!loading && rewards.map((reward) => {
                const canApprove = reward.status === 'PENDING';
                const canReject = reward.status === 'PENDING';
                const canRedeem = reward.status === 'AVAILABLE' || reward.status === 'CLAIMED';
                const canCancel = !['REDEEMED', 'CANCELLED', 'EXPIRED'].includes(reward.status);
                const noActions = !canApprove && !canReject && !canRedeem && !canCancel;
                const pastDue = isPastExpiry(reward);

                return (
                  <TableRow key={reward.id} className="hover:bg-slate-50/50 transition-colors">
                    <TableCell className="font-medium">{reward.rewardCode}</TableCell>
                    <TableCell>{reward.memberId}</TableCell>
                    <TableCell>
                      <Badge variant="outline" className={reward.memberType === 'REFERRER' ? 'bg-blue-50 text-blue-700' : 'bg-purple-50 text-purple-700'}>
                        {reward.memberType === 'REFERRER' ? 'Referrer' : 'Referee'}
                      </Badge>
                    </TableCell>
                    <TableCell>{reward.rewardRuleId ?? '—'}</TableCell>
                    <TableCell>{REWARD_TYPE_LABELS[reward.rewardType] ?? reward.rewardType}</TableCell>
                    <TableCell>{formatRewardValue(reward)}</TableCell>
                    <TableCell>
                      <Badge className={STATUS_BADGE_CLASS[reward.status] ?? 'bg-gray-100 text-gray-800'}>
                        {reward.status}
                      </Badge>
                    </TableCell>
                    <TableCell className="text-sm">{approvalDisplay(reward)}</TableCell>
                    <TableCell className={pastDue ? 'text-red-600 font-medium' : ''}>
                      {formatDate(reward.expiryDate)}
                    </TableCell>
                    <TableCell>{formatDate(reward.generatedDate)}</TableCell>
                    <TableCell>{formatDate(reward.redeemedDate)}</TableCell>
                    <TableCell className="text-right">
                      <DropdownMenu>
                        <DropdownMenuTrigger asChild>
                          <Button variant="ghost" className="h-8 w-8 p-0">
                            <MoreHorizontal className="h-4 w-4" />
                          </Button>
                        </DropdownMenuTrigger>
                        <DropdownMenuContent align="end">
                          {canApprove && (
                            <DropdownMenuItem onClick={() => openAction('approve', reward)}>
                              <CheckCircle className="mr-2 h-4 w-4 text-green-600" /> Approve
                            </DropdownMenuItem>
                          )}
                          {canReject && (
                            <DropdownMenuItem onClick={() => openAction('reject', reward)}>
                              <XCircle className="mr-2 h-4 w-4 text-red-600" /> Reject
                            </DropdownMenuItem>
                          )}
                          {canRedeem && (
                            <DropdownMenuItem onClick={() => handleMarkRedeemed(reward)}>
                              <PackageCheck className="mr-2 h-4 w-4 text-blue-600" /> Mark Redeemed
                            </DropdownMenuItem>
                          )}
                          {canCancel && (
                            <>
                              <DropdownMenuSeparator />
                              <DropdownMenuItem className="text-red-600" onClick={() => openAction('cancel', reward)}>
                                <Ban className="mr-2 h-4 w-4" /> Cancel
                              </DropdownMenuItem>
                            </>
                          )}
                          {noActions && (
                            <DropdownMenuItem disabled>No actions available</DropdownMenuItem>
                          )}
                        </DropdownMenuContent>
                      </DropdownMenu>
                    </TableCell>
                  </TableRow>
                );
              })}
            </TableBody>
          </Table>
        </CardContent>
      </Card>

      {/* Pagination */}
      {totalPages > 1 && (
        <div className="flex items-center justify-between mt-2">
          <div className="text-sm text-muted-foreground">
            Showing {((currentPage - 1) * PAGE_SIZE) + 1} to {Math.min(currentPage * PAGE_SIZE, totalItems)} of {totalItems} rewards
          </div>
          <div className="flex items-center space-x-2">
            <Button
              variant="outline"
              size="sm"
              onClick={() => setCurrentPage((p) => Math.max(1, p - 1))}
              disabled={currentPage === 1}
            >
              <ChevronLeft className="h-4 w-4 mr-1" /> Previous
            </Button>
            <div className="text-sm">Page {currentPage} of {totalPages}</div>
            <Button
              variant="outline"
              size="sm"
              onClick={() => setCurrentPage((p) => Math.min(totalPages, p + 1))}
              disabled={currentPage === totalPages}
            >
              Next <ChevronRight className="h-4 w-4 ml-1" />
            </Button>
          </div>
        </div>
      )}

      {/* Approve / Reject / Cancel confirmation dialog */}
      <Dialog open={!!actionDialog} onOpenChange={(open) => { if (!open) setActionDialog(null); }}>
        <DialogContent className="max-w-md">
          <DialogHeader>
            <DialogTitle>{actionDialog ? ACTION_LABEL[actionDialog.type] : ''} Reward</DialogTitle>
            <DialogDescription>
              {actionDialog && (
                <>
                  {ACTION_LABEL[actionDialog.type]} reward <strong>{actionDialog.reward.rewardCode}</strong> for member{' '}
                  <strong>{actionDialog.reward.memberId}</strong>. You can optionally add remarks below.
                </>
              )}
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-2">
            <Label htmlFor="action-remarks">Remarks (optional)</Label>
            <Textarea
              id="action-remarks"
              value={remarks}
              onChange={(e) => setRemarks(e.target.value)}
              placeholder="Add a note for the audit trail..."
              rows={3}
            />
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setActionDialog(null)} disabled={processing}>
              Cancel
            </Button>
            <Button
              onClick={confirmAction}
              disabled={processing}
              className={actionDialog?.type === 'reject' || actionDialog?.type === 'cancel' ? 'bg-red-600 hover:bg-red-700 text-white' : ''}
            >
              {processing ? 'Processing...' : `Confirm ${actionDialog ? ACTION_LABEL[actionDialog.type] : ''}`}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
