/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "osvzkanbfwvrbfmmhens"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9zdnprYW5iZnd2cmJmbW1oZW5zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3ODUyMjAsImV4cCI6MjA3NDM2MTIyMH0.yFLWQYTZa4Tb0M_xZCPjK06xddBA-eHTO2OQREUHNTQ"
