-- ============================================================
-- V1: Control-Plane Foundation (Phase 1 multi-tenant groundwork)
-- Creates the tenant-registry schema in the new, isolated
-- gymbios_control database. Inert in this phase: no application
-- code reads/writes these tables during normal request handling
-- yet (see ControlPlaneDataSourceConfig + TenantBackfillRunner).
-- Column/audit conventions mirror the primary DB's BaseEntity
-- pattern (created_at/updated_at/created_by/updated_by), but
-- these entities do NOT extend the primary com.company.project
-- .entities.BaseEntity (that class's @EntityListeners/@FilterDef
-- are branch-scoped concepts meaningless to control-plane data).
-- ============================================================

CREATE TABLE IF NOT EXISTS tenants (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255) NOT NULL,
    slug            VARCHAR(100) NOT NULL UNIQUE,
    status          VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    owner_user_id   BIGINT,
    created_at      TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP,
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS tenant_connections (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id           BIGINT NOT NULL REFERENCES tenants(id),
    db_host             VARCHAR(255),
    db_port             INTEGER,
    db_name             VARCHAR(255),
    db_username         VARCHAR(255),
    db_credential_enc   TEXT,
    created_at          TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP,
    created_by          VARCHAR(255),
    updated_by          VARCHAR(255)
);

CREATE INDEX IF NOT EXISTS idx_tenant_connections_tenant_id ON tenant_connections (tenant_id);

CREATE TABLE IF NOT EXISTS tenant_stats (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id           BIGINT NOT NULL REFERENCES tenants(id),
    branch_count        INTEGER NOT NULL DEFAULT 0,
    active_user_count   INTEGER NOT NULL DEFAULT 0,
    owner_username      VARCHAR(255),
    last_synced_at      TIMESTAMP,
    created_at          TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP,
    created_by          VARCHAR(255),
    updated_by          VARCHAR(255)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_tenant_stats_tenant_id ON tenant_stats (tenant_id);

CREATE TABLE IF NOT EXISTS tenant_provisioning_log (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT NOT NULL REFERENCES tenants(id),
    step            VARCHAR(100) NOT NULL,
    error_message   TEXT,
    attempted_at    TIMESTAMP NOT NULL DEFAULT NOW(),
    created_at      TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP,
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255)
);

CREATE INDEX IF NOT EXISTS idx_tenant_provisioning_log_tenant_id ON tenant_provisioning_log (tenant_id);

CREATE TABLE IF NOT EXISTS platform_users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR(255) NOT NULL UNIQUE,
    email           VARCHAR(255) UNIQUE,
    password_hash   VARCHAR(255) NOT NULL,
    status          VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at      TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP,
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255)
);
