-- ============================================================
-- V2: User Directory (Phase 5 login resolution)
-- A lightweight cross-tenant lookup so login can resolve which
-- tenant database a username/email lives in BEFORE authenticating
-- against it. A user absent from this table is resolved via the
-- default/primary DataSource exactly as before this phase (e.g.
-- GYMBIOS_ADMIN, or any account not yet migrated/provisioned into
-- its own tenant database) — no separate flag needed.
-- ============================================================

CREATE TABLE IF NOT EXISTS user_directory (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR(255) NOT NULL UNIQUE,
    email           VARCHAR(255) NOT NULL UNIQUE,
    tenant_slug     VARCHAR(100) NOT NULL,
    created_at      TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP,
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255)
);

CREATE INDEX IF NOT EXISTS idx_user_directory_tenant_slug ON user_directory (tenant_slug);
