-- ============================================================
-- V4: Platform lead pipeline (Super Admin's gym-signup CRM)
-- Prospective gyms that submit the public "Request a demo" onboarding
-- form on the pricing page land here as stage='LEAD', are worked by
-- GYMBIOS_ADMIN through follow-ups, then move to stage='PENDING_APPROVAL'
-- and finally stage='APPROVED' once a real gym is created via the
-- existing POST /api/gyms flow (see GymController/GymService — this
-- table does not duplicate gym-creation logic, it only tracks the
-- pipeline up to that point and records the resulting tenant/gym id).
--
-- Lives in the control-plane DB, not any tenant DB: these are prospects
-- for GymBios itself, not any single gym's own member leads (compare
-- the unrelated per-tenant "leads" table in the primary/tenant schema).
-- Column/audit conventions mirror the other control-plane tables
-- (created_at/updated_at/created_by/updated_by).
-- ============================================================

CREATE TABLE IF NOT EXISTS platform_leads (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Pipeline state. LEAD -> PENDING_APPROVAL -> APPROVED, or REJECTED/LOST
    -- from LEAD or PENDING_APPROVAL. Plain unconstrained VARCHAR, same
    -- application-level-enum convention as tenants.status.
    stage                   VARCHAR(20) NOT NULL DEFAULT 'LEAD',
    -- Sub-status while stage = 'LEAD': NEW / CONTACTED / FOLLOW_UP.
    -- Meaningless once the record leaves LEAD; left as-is (not nulled)
    -- so the lead's last worked state stays visible in history.
    lead_status             VARCHAR(20) NOT NULL DEFAULT 'NEW',

    -- Captured from business-onboarding-fullscreen.tsx's BusinessOnboardingData
    business_name           VARCHAR(255) NOT NULL,
    plan_interest           VARCHAR(100),
    business_types          TEXT,   -- JSON array, same convention as tenant Lead.tags (JsonStringListConverter)
    years_in_business       VARCHAR(100),
    country                 VARCHAR(255),
    state                   VARCHAR(255),
    city_area               VARCHAR(255),
    address                 TEXT,
    branches                VARCHAR(50),
    member_count            VARCHAR(50),
    staff_count             VARCHAR(50),
    services                TEXT,   -- JSON array
    current_software        VARCHAR(255),
    reasons_to_switch       TEXT,   -- JSON array
    goals                   TEXT,   -- JSON array
    contact_name            VARCHAR(255),
    contact_email           VARCHAR(255),
    contact_phone           VARCHAR(50),
    contact_whatsapp        VARCHAR(50),
    notes                   TEXT,

    source                  VARCHAR(255) NOT NULL DEFAULT 'Pricing page onboarding',
    -- IP of the submitting request, for the abuse/rate-limit story — never shown
    -- in the UI, diagnostic only.
    submitted_from_ip       VARCHAR(64),

    -- Set once approved into a real gym (Pending Approval's final step calls the
    -- existing POST /api/gyms, then PATCH .../approve on this record with the result).
    gym_tenant_id           BIGINT REFERENCES tenants(id),
    gym_slug                VARCHAR(100),
    approved_at             TIMESTAMP,

    created_at              TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMP,
    created_by              VARCHAR(255),
    updated_by              VARCHAR(255)
);

CREATE INDEX IF NOT EXISTS idx_platform_leads_stage ON platform_leads (stage);
CREATE INDEX IF NOT EXISTS idx_platform_leads_created_at ON platform_leads (created_at);

CREATE TABLE IF NOT EXISTS platform_lead_follow_ups (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform_lead_id    BIGINT NOT NULL REFERENCES platform_leads(id) ON DELETE CASCADE,
    type                VARCHAR(20) NOT NULL,   -- CALL / EMAIL / MEETING
    due_date            TIMESTAMP NOT NULL,
    notes               TEXT,
    status              VARCHAR(20) NOT NULL DEFAULT 'PENDING',  -- PENDING / COMPLETED (OVERDUE is derived from due_date, not stored)

    created_at          TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP,
    created_by          VARCHAR(255),
    updated_by          VARCHAR(255)
);

CREATE INDEX IF NOT EXISTS idx_platform_lead_follow_ups_lead_id ON platform_lead_follow_ups (platform_lead_id);
CREATE INDEX IF NOT EXISTS idx_platform_lead_follow_ups_due_date ON platform_lead_follow_ups (due_date);
