-- ============================================================
-- V5: Family Invitation Directory
-- Cross-tenant email -> (tenant, invitation) lookup for mobile Family/Couple
-- invitations. The invitation itself lives in the tenant database
-- (mobile_family_invitations); this row only lets the mobile app find it at
-- login from the caller's verified email, before it knows which tenant
-- database to route to (see MobileFamilyClaimController.claimPending).
-- ============================================================

CREATE TABLE IF NOT EXISTS family_invitation_directory (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_email VARCHAR(255) NOT NULL,
    tenant_slug     VARCHAR(100) NOT NULL,
    invitation_id   BIGINT NOT NULL,
    status          VARCHAR(50) NOT NULL, -- PENDING, CLAIMED, SKIPPED, REVOKED, INVALID
    gym_name        VARCHAR(255),
    inviter_name    VARCHAR(255),
    plan_name       VARCHAR(255),
    created_at      TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP,
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255),
    UNIQUE (tenant_slug, invitation_id)
);

CREATE INDEX IF NOT EXISTS idx_family_invitation_directory_email_status
    ON family_invitation_directory (recipient_email, status);
