-- Global Community store (control plane).
--
-- Visibility is global; moderation authority follows the author's gym
-- (author_tenant_slug). Identity is modelled explicitly in community_authors so
-- global user IDs and tenant-local user IDs are never compared directly.
--
-- Idempotent: every object uses IF NOT EXISTS / CREATE OR REPLACE / DROP ... IF
-- EXISTS, so re-running against a partially applied schema is safe. Nothing here
-- is read by the application until the rollout flags enable it.
--
-- Legacy rows carry their origin (legacy_source = 'primary' | 'tenant:<slug>',
-- legacy_id) directly, with a UNIQUE constraint, so "exactly one global row per
-- legacy row" is enforced by the database rather than by application code.

-- ── Identity ────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS community_authors (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind              VARCHAR(16)  NOT NULL,
    global_user_id    BIGINT,
    tenant_slug       VARCHAR(100),
    tenant_user_id    BIGINT,
    platform_user_id  BIGINT,
    display_name      VARCHAR(120) NOT NULL,
    avatar_url        TEXT,
    primary_role      VARCHAR(64),
    status            VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE',
    created_at        TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMP,
    CONSTRAINT ck_community_authors_kind CHECK (kind IN ('GLOBAL', 'TENANT', 'PLATFORM')),
    CONSTRAINT ck_community_authors_status CHECK (status IN ('ACTIVE', 'SUSPENDED')),
    CONSTRAINT ck_community_authors_identity CHECK (
        (kind = 'GLOBAL'   AND global_user_id IS NOT NULL AND tenant_slug IS NULL AND tenant_user_id IS NULL AND platform_user_id IS NULL)
     OR (kind = 'TENANT'   AND global_user_id IS NULL AND tenant_slug IS NOT NULL AND tenant_user_id IS NOT NULL AND platform_user_id IS NULL)
     OR (kind = 'PLATFORM' AND global_user_id IS NULL AND tenant_slug IS NULL AND tenant_user_id IS NULL AND platform_user_id IS NOT NULL)
    ),
    CONSTRAINT ck_community_authors_slug CHECK (tenant_slug IS NULL OR (tenant_slug <> '' AND tenant_slug !~ '\s'))
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_community_authors_global
    ON community_authors (global_user_id) WHERE kind = 'GLOBAL';
CREATE UNIQUE INDEX IF NOT EXISTS ux_community_authors_tenant
    ON community_authors (tenant_slug, tenant_user_id) WHERE kind = 'TENANT';
CREATE UNIQUE INDEX IF NOT EXISTS ux_community_authors_platform
    ON community_authors (platform_user_id) WHERE kind = 'PLATFORM';

-- ── Posts ───────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS global_community_posts (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000000000) PRIMARY KEY,
    author_id            BIGINT       NOT NULL REFERENCES community_authors (id),
    author_tenant_slug   VARCHAR(100) NOT NULL,
    author_branch_id     BIGINT,
    author_member_id     BIGINT,
    author_gym_name      VARCHAR(255),
    author_branch_name   VARCHAR(255),
    topic                VARCHAR(140) NOT NULL,
    content              TEXT         NOT NULL,
    type                 VARCHAR(32)  NOT NULL,
    visibility           VARCHAR(16)  NOT NULL DEFAULT 'PUBLIC',
    status               VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE',
    origin               VARCHAR(16)  NOT NULL,
    like_count           INTEGER      NOT NULL DEFAULT 0,
    comment_count        INTEGER      NOT NULL DEFAULT 0,
    hidden_at            TIMESTAMP,
    hidden_by_author_id  BIGINT REFERENCES community_authors (id),
    hidden_reason        VARCHAR(500),
    archived_at          TIMESTAMP,
    deleted_at           TIMESTAMP,
    legacy_source        VARCHAR(120),
    legacy_id            BIGINT,
    legacy_fingerprint   VARCHAR(64),
    created_at           TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMP,
    CONSTRAINT ck_gcp_visibility CHECK (visibility IN ('PUBLIC', 'GYM')),
    CONSTRAINT ck_gcp_status CHECK (status IN ('ACTIVE', 'ARCHIVED', 'HIDDEN', 'DELETED')),
    CONSTRAINT ck_gcp_origin CHECK (origin IN ('LEGACY', 'GLOBAL')),
    CONSTRAINT ck_gcp_counters CHECK (like_count >= 0 AND comment_count >= 0),
    CONSTRAINT ck_gcp_slug CHECK (author_tenant_slug <> '' AND author_tenant_slug !~ '\s'),
    CONSTRAINT ck_gcp_legacy CHECK (
        (origin = 'LEGACY' AND legacy_source IS NOT NULL AND legacy_id IS NOT NULL AND legacy_fingerprint IS NOT NULL)
     OR (origin = 'GLOBAL' AND legacy_source IS NULL AND legacy_id IS NULL AND legacy_fingerprint IS NULL)
    ),
    -- New content obeys the approved limits; migrated legacy content is kept verbatim.
    CONSTRAINT ck_gcp_content_limit CHECK (origin = 'LEGACY' OR char_length(content) <= 1000),
    CONSTRAINT ck_gcp_hidden_state CHECK (status <> 'HIDDEN' OR (hidden_at IS NOT NULL AND hidden_by_author_id IS NOT NULL)),
    CONSTRAINT ck_gcp_deleted_state CHECK (status <> 'DELETED' OR deleted_at IS NOT NULL),
    CONSTRAINT ux_gcp_legacy UNIQUE (legacy_source, legacy_id)
);

CREATE INDEX IF NOT EXISTS ix_gcp_public_feed
    ON global_community_posts (created_at DESC, id DESC) WHERE status = 'ACTIVE' AND visibility = 'PUBLIC';
CREATE INDEX IF NOT EXISTS ix_gcp_gym_feed
    ON global_community_posts (author_tenant_slug, created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS ix_gcp_author
    ON global_community_posts (author_id, created_at DESC, id DESC);

CREATE TABLE IF NOT EXISTS global_community_post_images (
    post_id        BIGINT      PRIMARY KEY REFERENCES global_community_posts (id),
    origin         VARCHAR(16) NOT NULL,
    content_type   VARCHAR(64) NOT NULL,
    data           BYTEA       NOT NULL,
    byte_size      INTEGER     NOT NULL,
    width          INTEGER,
    height         INTEGER,
    aspect_ratio   VARCHAR(8),
    crop_position  INTEGER,
    crop_zoom      INTEGER,
    sha256         CHAR(64)    NOT NULL,
    created_at     TIMESTAMP   NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_gcpi_origin CHECK (origin IN ('LEGACY', 'GLOBAL')),
    CONSTRAINT ck_gcpi_type CHECK (content_type LIKE 'image/%'),
    CONSTRAINT ck_gcpi_size CHECK (byte_size > 0 AND byte_size = octet_length(data)),
    CONSTRAINT ck_gcpi_dimensions CHECK ((width IS NULL OR width > 0) AND (height IS NULL OR height > 0)),
    -- C9 limits for new uploads: one JPEG/PNG, <= 1.5 MB decoded, <= 2048x2048.
    CONSTRAINT ck_gcpi_new_upload_limits CHECK (
        origin = 'LEGACY'
     OR (content_type IN ('image/jpeg', 'image/png') AND byte_size <= 1572864
         AND width IS NOT NULL AND height IS NOT NULL AND width <= 2048 AND height <= 2048)
    )
);

-- ── Comments and likes ──────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS global_community_comments (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000000000) PRIMARY KEY,
    post_id             BIGINT       NOT NULL REFERENCES global_community_posts (id),
    author_id           BIGINT       NOT NULL REFERENCES community_authors (id),
    author_tenant_slug  VARCHAR(100) NOT NULL,
    author_member_id    BIGINT,
    content             TEXT         NOT NULL,
    status              VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE',
    origin              VARCHAR(16)  NOT NULL,
    deleted_at          TIMESTAMP,
    legacy_source       VARCHAR(120),
    legacy_id           BIGINT,
    legacy_fingerprint  VARCHAR(64),
    created_at          TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP,
    -- Moderator hides live in community_comment_hides (two independent scopes),
    -- so a comment's own status only records the author's deletion.
    CONSTRAINT ck_gcc_status CHECK (status IN ('ACTIVE', 'DELETED')),
    CONSTRAINT ck_gcc_origin CHECK (origin IN ('LEGACY', 'GLOBAL')),
    CONSTRAINT ck_gcc_slug CHECK (author_tenant_slug <> '' AND author_tenant_slug !~ '\s'),
    CONSTRAINT ck_gcc_legacy CHECK (
        (origin = 'LEGACY' AND legacy_source IS NOT NULL AND legacy_id IS NOT NULL AND legacy_fingerprint IS NOT NULL)
     OR (origin = 'GLOBAL' AND legacy_source IS NULL AND legacy_id IS NULL AND legacy_fingerprint IS NULL)
    ),
    CONSTRAINT ck_gcc_content_limit CHECK (origin = 'LEGACY' OR char_length(content) <= 500),
    CONSTRAINT ck_gcc_deleted_state CHECK (status <> 'DELETED' OR deleted_at IS NOT NULL),
    CONSTRAINT ux_gcc_legacy UNIQUE (legacy_source, legacy_id)
);

CREATE INDEX IF NOT EXISTS ix_gcc_post ON global_community_comments (post_id, created_at, id);
CREATE INDEX IF NOT EXISTS ix_gcc_author_gym ON global_community_comments (author_tenant_slug, created_at DESC);

CREATE TABLE IF NOT EXISTS global_community_likes (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000000000) PRIMARY KEY,
    post_id             BIGINT      NOT NULL REFERENCES global_community_posts (id),
    author_id           BIGINT      NOT NULL REFERENCES community_authors (id),
    origin              VARCHAR(16) NOT NULL,
    legacy_source       VARCHAR(120),
    legacy_id           BIGINT,
    legacy_fingerprint  VARCHAR(64),
    created_at          TIMESTAMP   NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_gcl_origin CHECK (origin IN ('LEGACY', 'GLOBAL')),
    CONSTRAINT ck_gcl_legacy CHECK (
        (origin = 'LEGACY' AND legacy_source IS NOT NULL AND legacy_id IS NOT NULL AND legacy_fingerprint IS NOT NULL)
     OR (origin = 'GLOBAL' AND legacy_source IS NULL AND legacy_id IS NULL AND legacy_fingerprint IS NULL)
    ),
    CONSTRAINT ux_gcl_post_author UNIQUE (post_id, author_id),
    CONSTRAINT ux_gcl_legacy UNIQUE (legacy_source, legacy_id)
);

CREATE INDEX IF NOT EXISTS ix_gcl_author ON global_community_likes (author_id);

-- ── Moderation ──────────────────────────────────────────────────────────────

-- Two independent hide scopes for comments (C5). A comment is hidden while any
-- row exists; each scope can only remove its own row.
CREATE TABLE IF NOT EXISTS community_comment_hides (
    comment_id           BIGINT       NOT NULL REFERENCES global_community_comments (id),
    scope                VARCHAR(20)  NOT NULL,
    scope_tenant_slug    VARCHAR(100),
    hidden_by_author_id  BIGINT       NOT NULL REFERENCES community_authors (id),
    reason               VARCHAR(500),
    created_at           TIMESTAMP    NOT NULL DEFAULT NOW(),
    PRIMARY KEY (comment_id, scope),
    CONSTRAINT ck_cch_scope CHECK (scope IN ('AUTHOR_GYM', 'POST_OWNER_GYM', 'PLATFORM')),
    CONSTRAINT ck_cch_scope_slug CHECK ((scope = 'PLATFORM') = (scope_tenant_slug IS NULL))
);

CREATE TABLE IF NOT EXISTS community_moderation_actions (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_type       VARCHAR(16)  NOT NULL,
    target_id         BIGINT       NOT NULL,
    action            VARCHAR(24)  NOT NULL,
    scope             VARCHAR(20)  NOT NULL,
    actor_author_id   BIGINT       NOT NULL REFERENCES community_authors (id),
    actor_tenant_slug VARCHAR(100),
    reason            VARCHAR(500),
    created_at        TIMESTAMP    NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_cma_target CHECK (target_type IN ('POST', 'COMMENT', 'REPORT')),
    CONSTRAINT ck_cma_action CHECK (action IN ('HIDE', 'RESTORE', 'ARCHIVE', 'UNARCHIVE', 'DELETE',
                                               'RESOLVE_REPORT', 'DISMISS_REPORT', 'ESCALATE_REPORT')),
    CONSTRAINT ck_cma_scope CHECK (scope IN ('AUTHOR', 'AUTHOR_GYM', 'POST_OWNER_GYM', 'PLATFORM', 'SYSTEM'))
);

CREATE INDEX IF NOT EXISTS ix_cma_target ON community_moderation_actions (target_type, target_id, created_at);

CREATE TABLE IF NOT EXISTS community_reports (
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_type                VARCHAR(16)  NOT NULL,
    target_id                  BIGINT       NOT NULL,
    reporter_author_id         BIGINT       NOT NULL REFERENCES community_authors (id),
    reason                     VARCHAR(32)  NOT NULL,
    details                    VARCHAR(500),
    target_author_tenant_slug  VARCHAR(100) NOT NULL,
    context_tenant_slug        VARCHAR(100),
    status                     VARCHAR(16)  NOT NULL DEFAULT 'OPEN',
    resolved_by_author_id      BIGINT REFERENCES community_authors (id),
    resolved_scope             VARCHAR(20),
    resolved_at                TIMESTAMP,
    created_at                 TIMESTAMP    NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_cr_target CHECK (target_type IN ('POST', 'COMMENT')),
    CONSTRAINT ck_cr_reason CHECK (reason IN ('SPAM', 'HARASSMENT', 'HATE', 'NUDITY', 'VIOLENCE', 'SELF_HARM', 'OTHER')),
    CONSTRAINT ck_cr_status CHECK (status IN ('OPEN', 'RESOLVED', 'DISMISSED', 'ESCALATED')),
    CONSTRAINT ck_cr_resolution CHECK (
        (status IN ('OPEN', 'ESCALATED') AND resolved_at IS NULL)
     OR (status IN ('RESOLVED', 'DISMISSED') AND resolved_at IS NOT NULL AND resolved_by_author_id IS NOT NULL)
    ),
    CONSTRAINT ck_cr_context CHECK (target_type = 'COMMENT' OR context_tenant_slug IS NULL),
    CONSTRAINT ux_cr_reporter UNIQUE (target_type, target_id, reporter_author_id)
);

CREATE INDEX IF NOT EXISTS ix_cr_author_gym ON community_reports (target_author_tenant_slug, status, created_at);
CREATE INDEX IF NOT EXISTS ix_cr_context_gym ON community_reports (context_tenant_slug, status, created_at);

-- ── Migration bookkeeping ───────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS community_migration_runs (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind           VARCHAR(16)  NOT NULL,
    mode           VARCHAR(16)  NOT NULL,
    status         VARCHAR(16)  NOT NULL,
    triggered_by   VARCHAR(255) NOT NULL,
    legacy_digest  VARCHAR(64),
    summary        TEXT,
    started_at     TIMESTAMP    NOT NULL DEFAULT NOW(),
    finished_at    TIMESTAMP,
    CONSTRAINT ck_cmr_kind CHECK (kind IN ('BACKFILL', 'RECONCILE')),
    CONSTRAINT ck_cmr_mode CHECK (mode IN ('FULL', 'DELTA', 'FINAL')),
    CONSTRAINT ck_cmr_status CHECK (status IN ('RUNNING', 'COMPLETED', 'PASS', 'FAIL', 'ERROR')),
    CONSTRAINT ck_cmr_finished CHECK (status = 'RUNNING' OR finished_at IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS community_migration_quarantine (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_source   VARCHAR(120) NOT NULL,
    legacy_table    VARCHAR(64)  NOT NULL,
    legacy_id       BIGINT       NOT NULL,
    code            VARCHAR(64)  NOT NULL,
    detail          TEXT         NOT NULL,
    status          VARCHAR(24)  NOT NULL DEFAULT 'OPEN',
    resolution      TEXT,
    resolved_by     VARCHAR(255),
    resolved_at     TIMESTAMP,
    first_seen_at   TIMESTAMP    NOT NULL DEFAULT NOW(),
    last_seen_at    TIMESTAMP    NOT NULL DEFAULT NOW(),
    last_run_id     BIGINT REFERENCES community_migration_runs (id),
    CONSTRAINT ck_cmq_table CHECK (legacy_table IN ('community_posts', 'community_post_comments', 'community_post_likes')),
    CONSTRAINT ck_cmq_status CHECK (status IN ('OPEN', 'RESOLVED', 'APPROVED_EXCLUSION')),
    CONSTRAINT ck_cmq_resolution CHECK (
        status = 'OPEN' OR (resolution IS NOT NULL AND resolved_by IS NOT NULL AND resolved_at IS NOT NULL)
    ),
    CONSTRAINT ux_cmq_record UNIQUE (legacy_source, legacy_table, legacy_id, code)
);

-- ── Rollout controls ────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS community_rollout_state (
    id                              SMALLINT     PRIMARY KEY DEFAULT 1,
    authority                       VARCHAR(8)   NOT NULL DEFAULT 'LEGACY',
    write_mode                      VARCHAR(16)  NOT NULL DEFAULT 'OPEN',
    op_post                         BOOLEAN      NOT NULL DEFAULT FALSE,
    op_comment                      BOOLEAN      NOT NULL DEFAULT FALSE,
    op_like                         BOOLEAN      NOT NULL DEFAULT FALSE,
    op_report                       BOOLEAN      NOT NULL DEFAULT FALSE,
    global_reads                    BOOLEAN      NOT NULL DEFAULT FALSE,
    moderation                      BOOLEAN      NOT NULL DEFAULT FALSE,
    reports                         BOOLEAN      NOT NULL DEFAULT FALSE,
    shadow_compare                  BOOLEAN      NOT NULL DEFAULT FALSE,
    legacy_delta_sync               BOOLEAN      NOT NULL DEFAULT FALSE,
    mobile_surface                  VARCHAR(16)  NOT NULL DEFAULT 'OFF',
    web_surface                     VARCHAR(16)  NOT NULL DEFAULT 'OFF',
    production_baseline_accepted    BOOLEAN      NOT NULL DEFAULT FALSE,
    -- D1-D4: policies for facts only the production baseline can settle.
    -- Every default is the conservative choice: quarantine, never guess.
    platform_author_policy          VARCHAR(24)  NOT NULL DEFAULT 'QUARANTINE',
    unregistered_gym_policy         VARCHAR(24)  NOT NULL DEFAULT 'QUARANTINE',
    primary_member_login_policy     VARCHAR(24)  NOT NULL DEFAULT 'QUARANTINE',
    null_branch_policy              VARCHAR(24)  NOT NULL DEFAULT 'QUARANTINE',
    authority_changed_at            TIMESTAMP,
    updated_at                      TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_by                      VARCHAR(255) NOT NULL DEFAULT 'system',
    version                         INTEGER      NOT NULL DEFAULT 0,
    CONSTRAINT ck_crs_singleton CHECK (id = 1),
    CONSTRAINT ck_crs_authority CHECK (authority IN ('LEGACY', 'GLOBAL')),
    CONSTRAINT ck_crs_write_mode CHECK (write_mode IN ('OPEN', 'READ_ONLY')),
    CONSTRAINT ck_crs_mobile CHECK (mobile_surface IN ('OFF', 'ALLOWLIST', 'ALL')),
    CONSTRAINT ck_crs_web CHECK (web_surface IN ('OFF', 'ALLOWLIST', 'ALL')),
    CONSTRAINT ck_crs_platform_author CHECK (platform_author_policy IN ('QUARANTINE', 'EXCLUDE', 'MIGRATE_AS_PLATFORM')),
    CONSTRAINT ck_crs_unregistered_gym CHECK (unregistered_gym_policy IN ('QUARANTINE', 'ALLOW')),
    CONSTRAINT ck_crs_member_login CHECK (primary_member_login_policy IN ('QUARANTINE', 'TENANT')),
    CONSTRAINT ck_crs_null_branch CHECK (null_branch_policy IN ('QUARANTINE', 'GYM_LEVEL')),
    -- Global surfaces and writes are meaningless while the legacy store is authoritative.
    CONSTRAINT ck_crs_global_requires_authority CHECK (
        authority = 'GLOBAL'
     OR (NOT op_post AND NOT op_comment AND NOT op_like AND NOT op_report AND NOT global_reads
         AND NOT moderation AND NOT reports AND mobile_surface = 'OFF' AND web_surface = 'OFF')
    ),
    CONSTRAINT ck_crs_authority_gate CHECK (authority = 'LEGACY' OR production_baseline_accepted),
    CONSTRAINT ck_crs_shadow_only_legacy CHECK (authority = 'LEGACY' OR (NOT shadow_compare AND NOT legacy_delta_sync))
);

INSERT INTO community_rollout_state (id) VALUES (1) ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS community_rollout_allowlist (
    tenant_slug  VARCHAR(100) PRIMARY KEY,
    added_at     TIMESTAMP    NOT NULL DEFAULT NOW(),
    added_by     VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS community_rollout_audit (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    changed_at  TIMESTAMP    NOT NULL DEFAULT NOW(),
    changed_by  VARCHAR(255) NOT NULL,
    field       VARCHAR(64)  NOT NULL,
    old_value   TEXT,
    new_value   TEXT,
    reason      VARCHAR(500) NOT NULL
);

-- ── Guards ──────────────────────────────────────────────────────────────────

-- Append-only audit tables: rows can be inserted, never changed or removed.
CREATE OR REPLACE FUNCTION community_reject_mutation() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION '% is append-only', TG_TABLE_NAME;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_cma_append_only ON community_moderation_actions;
CREATE TRIGGER trg_cma_append_only BEFORE UPDATE OR DELETE ON community_moderation_actions
    FOR EACH ROW EXECUTE FUNCTION community_reject_mutation();
DROP TRIGGER IF EXISTS trg_cma_no_truncate ON community_moderation_actions;
CREATE TRIGGER trg_cma_no_truncate BEFORE TRUNCATE ON community_moderation_actions
    FOR EACH STATEMENT EXECUTE FUNCTION community_reject_mutation();

DROP TRIGGER IF EXISTS trg_cra_append_only ON community_rollout_audit;
CREATE TRIGGER trg_cra_append_only BEFORE UPDATE OR DELETE ON community_rollout_audit
    FOR EACH ROW EXECUTE FUNCTION community_reject_mutation();
DROP TRIGGER IF EXISTS trg_cra_no_truncate ON community_rollout_audit;
CREATE TRIGGER trg_cra_no_truncate BEFORE TRUNCATE ON community_rollout_audit
    FOR EACH STATEMENT EXECUTE FUNCTION community_reject_mutation();

-- Authority is one-way: once GLOBAL, the legacy tables can no longer represent
-- every Community identity, so reverting would lose data.
CREATE OR REPLACE FUNCTION community_rollout_state_guard() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'community_rollout_state cannot be deleted';
    END IF;
    IF OLD.authority = 'GLOBAL' AND NEW.authority <> 'GLOBAL' THEN
        RAISE EXCEPTION 'community authority cannot move from GLOBAL back to %', NEW.authority;
    END IF;
    IF OLD.production_baseline_accepted AND NOT NEW.production_baseline_accepted AND NEW.authority = 'GLOBAL' THEN
        RAISE EXCEPTION 'production baseline acceptance cannot be withdrawn after cutover';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_crs_guard ON community_rollout_state;
CREATE TRIGGER trg_crs_guard BEFORE UPDATE OR DELETE ON community_rollout_state
    FOR EACH ROW EXECUTE FUNCTION community_rollout_state_guard();
DROP TRIGGER IF EXISTS trg_crs_no_truncate ON community_rollout_state;
CREATE TRIGGER trg_crs_no_truncate BEFORE TRUNCATE ON community_rollout_state
    FOR EACH STATEMENT EXECUTE FUNCTION community_reject_mutation();
