-- ============================================================
-- V6: Lead capture forms (a gym's own social-media / ad lead forms)
-- A gym admin creates a form in the Leads page and gets a public link
-- (/f/{form_key}) to paste into Facebook/Instagram/Google ads, bios,
-- WhatsApp status, etc. Anyone submitting that link has no session, so
-- the unguessable form_key is the only thing that tells the public
-- endpoint which tenant database + branch the resulting lead belongs to.
--
-- Lives in the control-plane DB (not a tenant DB) for exactly that
-- reason: the public request must resolve form_key -> tenant BEFORE any
-- tenant DataSource can be chosen. The lead itself is still written to
-- the tenant's own "leads" table (see LeadCaptureSubmissionService);
-- this table only holds the form's configuration + submission counters.
-- Column/audit conventions mirror the other control-plane tables.
-- ============================================================

CREATE TABLE IF NOT EXISTS lead_capture_forms (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    form_key            VARCHAR(32)  NOT NULL UNIQUE,
    tenant_slug         VARCHAR(100) NOT NULL,
    -- Tenant-DB branches.id; not a FK since it lives in another database.
    branch_id           BIGINT       NOT NULL,

    name                VARCHAR(255) NOT NULL,   -- internal, e.g. "Diwali Instagram Offer"
    headline            VARCHAR(255),            -- shown on the public page
    description         TEXT,
    success_message     TEXT,
    -- Gym's own privacy policy, linked next to the consent checkbox (ad platforms
    -- such as Meta require one on lead forms). Falls back to the GymBios policy.
    privacy_policy_url  VARCHAR(500),

    -- Defaults applied to every lead this form creates. source uses the
    -- same values as the tenant Lead.source (facebook-ads / instagram /
    -- google-ads / social-media / website / other); a recognised
    -- utm_source on the link overrides it per submission.
    source              VARCHAR(50)  NOT NULL DEFAULT 'social-media',
    assigned_staff      VARCHAR(255),

    show_email          BOOLEAN      NOT NULL DEFAULT TRUE,
    require_email       BOOLEAN      NOT NULL DEFAULT FALSE,
    show_interest       BOOLEAN      NOT NULL DEFAULT TRUE,

    active              BOOLEAN      NOT NULL DEFAULT TRUE,
    submission_count    BIGINT       NOT NULL DEFAULT 0,
    last_submission_at  TIMESTAMP,

    created_at          TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP,
    created_by          VARCHAR(255),
    updated_by          VARCHAR(255)
);

CREATE INDEX IF NOT EXISTS idx_lead_capture_forms_tenant ON lead_capture_forms (tenant_slug, branch_id);
