-- ============================================================
-- V7: User Memberships (global account -> gyms it is a member of)
-- Cross-tenant index of which tenant databases hold a members row linked
-- to a GymBios app account (members.global_user_id). Lets a request in
-- one gym find the caller's memberships in other gyms without scanning
-- every tenant database — first used by Community, where any active
-- membership at any gym unlocks liking and commenting in every gym's feed.
--
-- Deliberately holds only the link, not the membership's status: status
-- changes (approval, freeze, expiry by date) happen without an event to
-- mirror here, so callers check it live in the few tenant databases this
-- table points them to. A row whose members row was later deleted or
-- unlinked is harmless — the live check simply finds nothing there.
--
-- This is the index sketched in docs/mobile-multi-membership-switcher-plan.md;
-- the switcher's display columns can be added when that work starts.
-- ============================================================

CREATE TABLE IF NOT EXISTS user_memberships (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    global_user_id  BIGINT       NOT NULL,
    tenant_slug     VARCHAR(100) NOT NULL,
    -- Tenant-DB members.id; not a FK since it lives in another database.
    member_id       BIGINT       NOT NULL,
    created_at      TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP,
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255),
    -- The backend assumes one members row per global user per tenant.
    UNIQUE (global_user_id, tenant_slug)
);

CREATE INDEX IF NOT EXISTS idx_user_memberships_global_user_id ON user_memberships (global_user_id);
