-- Administration module: fine-grained module/action permissions on top of the
-- existing flat Role/UserRole RBAC. A Role now owns a set of Permission rows
-- (via role_permissions) instead of only gating a handful of URL prefixes in
-- SecurityConfig. ADMIN keeps behaving as "all permissions" in application
-- code (see RoleService.getEffectivePermissionKeys) rather than being backed
-- by rows here, so it never needs to be kept in sync with the catalog.

ALTER TABLE roles ADD COLUMN description VARCHAR(255);
ALTER TABLE roles ADD COLUMN is_system BOOLEAN NOT NULL DEFAULT FALSE;

CREATE TABLE permissions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permission_key  VARCHAR(100) NOT NULL UNIQUE,
    module          VARCHAR(50) NOT NULL,
    action          VARCHAR(20) NOT NULL,
    description     VARCHAR(255),
    created_at      TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP,
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255)
);

CREATE TABLE role_permissions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id         BIGINT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    permission_id   BIGINT NOT NULL REFERENCES permissions(id) ON DELETE CASCADE,
    created_at      TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP,
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255),
    CONSTRAINT uq_role_permission UNIQUE (role_id, permission_id)
);

CREATE INDEX idx_role_permissions_role_id ON role_permissions(role_id);
