-- Makes 5 previously-global singleton settings tables branch-scoped:
-- financial_settings (COMPANY category + APP_PREFERENCES/currency_code key),
-- bios_settings, company_tax_details, attendance_report_settings, referral_settings.
-- Each was a single shared row for the whole install; branch_id (nullable) lets a
-- branch carry its own row while leaving truly-global settings (financial_settings
-- rows outside COMPANY/APP_PREFERENCES) untouched with branch_id = NULL.

ALTER TABLE financial_settings DROP CONSTRAINT IF EXISTS uk_iyi84uyi5ghx1e1i2ctuvm739;
ALTER TABLE financial_settings ADD COLUMN IF NOT EXISTS branch_id BIGINT;
CREATE UNIQUE INDEX IF NOT EXISTS uk_financial_settings_key_branch ON financial_settings (setting_key, branch_id) WHERE branch_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uk_financial_settings_key_global ON financial_settings (setting_key) WHERE branch_id IS NULL;

ALTER TABLE bios_settings ADD COLUMN IF NOT EXISTS branch_id BIGINT;
ALTER TABLE bios_settings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE bios_settings ALTER COLUMN id RESTART WITH 2;
CREATE UNIQUE INDEX IF NOT EXISTS uk_bios_settings_branch ON bios_settings (branch_id) WHERE branch_id IS NOT NULL;

ALTER TABLE company_tax_details ADD COLUMN IF NOT EXISTS branch_id BIGINT;
ALTER TABLE company_tax_details ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE company_tax_details ALTER COLUMN id RESTART WITH 2;
CREATE UNIQUE INDEX IF NOT EXISTS uk_company_tax_details_branch ON company_tax_details (branch_id) WHERE branch_id IS NOT NULL;

ALTER TABLE attendance_report_settings ADD COLUMN IF NOT EXISTS branch_id BIGINT;
ALTER TABLE attendance_report_settings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE attendance_report_settings ALTER COLUMN id RESTART WITH 2;
CREATE UNIQUE INDEX IF NOT EXISTS uk_attendance_report_settings_branch ON attendance_report_settings (branch_id) WHERE branch_id IS NOT NULL;

ALTER TABLE referral_settings ADD COLUMN IF NOT EXISTS branch_id BIGINT;
ALTER TABLE referral_settings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE referral_settings ALTER COLUMN id RESTART WITH 2;
CREATE UNIQUE INDEX IF NOT EXISTS uk_referral_settings_branch ON referral_settings (branch_id) WHERE branch_id IS NOT NULL;
