-- Makes 5 previously-global singleton settings tables branch-scoped:
-- financial_settings (COMPANY category + APP_PREFERENCES/currency_code key),
-- bios_settings, company_tax_details, attendance_report_settings, referral_settings.
-- Each was a single shared row for the whole install; branch_id (nullable) lets a
-- branch carry its own row while leaving truly-global settings (financial_settings
-- rows outside COMPANY/APP_PREFERENCES) untouched with branch_id = NULL.

ALTER TABLE financial_settings DROP CONSTRAINT IF EXISTS uk_iyi84uyi5ghx1e1i2ctuvm739;
ALTER TABLE financial_settings ADD COLUMN IF NOT EXISTS branch_id BIGINT;
CREATE UNIQUE INDEX IF NOT EXISTS uk_financial_settings_key_branch ON financial_settings (setting_key, branch_id) WHERE branch_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uk_financial_settings_key_global ON financial_settings (setting_key) WHERE branch_id IS NULL;

-- ALTER COLUMN id ADD GENERATED ... is guarded because a fresh database already
-- gives id a generated default (identity or sequence, depending on dialect)
-- straight from each entity's @GeneratedValue (Hibernate baseline runs before
-- this migration), and Postgres errors if asked to add identity to a column
-- that already has any default.
ALTER TABLE bios_settings ADD COLUMN IF NOT EXISTS branch_id BIGINT;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_attribute
        WHERE attrelid = 'bios_settings'::regclass AND attname = 'id' AND (attidentity <> '' OR atthasdef)
    ) THEN
        ALTER TABLE bios_settings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
        ALTER TABLE bios_settings ALTER COLUMN id RESTART WITH 2;
    END IF;
END $$;
CREATE UNIQUE INDEX IF NOT EXISTS uk_bios_settings_branch ON bios_settings (branch_id) WHERE branch_id IS NOT NULL;

ALTER TABLE company_tax_details ADD COLUMN IF NOT EXISTS branch_id BIGINT;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_attribute
        WHERE attrelid = 'company_tax_details'::regclass AND attname = 'id' AND (attidentity <> '' OR atthasdef)
    ) THEN
        ALTER TABLE company_tax_details ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
        ALTER TABLE company_tax_details ALTER COLUMN id RESTART WITH 2;
    END IF;
END $$;
CREATE UNIQUE INDEX IF NOT EXISTS uk_company_tax_details_branch ON company_tax_details (branch_id) WHERE branch_id IS NOT NULL;

ALTER TABLE attendance_report_settings ADD COLUMN IF NOT EXISTS branch_id BIGINT;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_attribute
        WHERE attrelid = 'attendance_report_settings'::regclass AND attname = 'id' AND (attidentity <> '' OR atthasdef)
    ) THEN
        ALTER TABLE attendance_report_settings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
        ALTER TABLE attendance_report_settings ALTER COLUMN id RESTART WITH 2;
    END IF;
END $$;
CREATE UNIQUE INDEX IF NOT EXISTS uk_attendance_report_settings_branch ON attendance_report_settings (branch_id) WHERE branch_id IS NOT NULL;

ALTER TABLE referral_settings ADD COLUMN IF NOT EXISTS branch_id BIGINT;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_attribute
        WHERE attrelid = 'referral_settings'::regclass AND attname = 'id' AND (attidentity <> '' OR atthasdef)
    ) THEN
        ALTER TABLE referral_settings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
        ALTER TABLE referral_settings ALTER COLUMN id RESTART WITH 2;
    END IF;
END $$;
CREATE UNIQUE INDEX IF NOT EXISTS uk_referral_settings_branch ON referral_settings (branch_id) WHERE branch_id IS NOT NULL;
