CREATE TABLE user_profiles (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    full_name VARCHAR(255) NOT NULL,
    phone VARCHAR(255),
    date_of_birth DATE,
    gender VARCHAR(50),
    nationality VARCHAR(100),
    address TEXT,
    photo_url TEXT,
    emergency_contact VARCHAR(255),
    emergency_phone VARCHAR(255),
    emergency_contact_name VARCHAR(255),
    emergency_contact_phone VARCHAR(255),
    blood_type VARCHAR(10),
    medical_conditions TEXT,
    allergies TEXT,
    current_medications TEXT,
    health_notes TEXT,
    chronic_illnesses TEXT,
    height DOUBLE PRECISION,
    weight DOUBLE PRECISION,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
