-- Plan Groups: the "Plan Type" classification on Manage Plans (Membership /
-- Class Package / Personal Training) used to be a hardcoded dropdown in the
-- frontend. This makes it an admin-managed, database-backed list instead, so
-- new groups can be added from the UI without a code change.

CREATE TABLE IF NOT EXISTS plan_groups (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL UNIQUE,
    status      VARCHAR(50) NOT NULL DEFAULT 'Active',
    created_at  TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMP,
    created_by  VARCHAR(255),
    updated_by  VARCHAR(255)
);

INSERT INTO plan_groups (name, status) VALUES
    ('Membership', 'Active'),
    ('Class Package', 'Active'),
    ('Personal Training', 'Active')
ON CONFLICT (name) DO NOTHING;
