ALTER TABLE branches 
ADD COLUMN IF NOT EXISTS lat DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS lng DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS center_type VARCHAR(255),
ADD COLUMN IF NOT EXISTS access_type VARCHAR(255),
ADD COLUMN IF NOT EXISTS operating_hours TEXT;
