ALTER TABLE members ADD COLUMN IF NOT EXISTS approval_status VARCHAR(20);
ALTER TABLE members ADD COLUMN IF NOT EXISTS approved_by VARCHAR(255);
ALTER TABLE members ADD COLUMN IF NOT EXISTS approved_at TIMESTAMP;
ALTER TABLE members ADD COLUMN IF NOT EXISTS rejection_reason TEXT;
CREATE INDEX IF NOT EXISTS idx_members_approval_status ON members(approval_status);

ALTER TABLE receipts ADD COLUMN IF NOT EXISTS approval_status VARCHAR(20);
ALTER TABLE receipts ADD COLUMN IF NOT EXISTS approved_by VARCHAR(255);
ALTER TABLE receipts ADD COLUMN IF NOT EXISTS approved_at TIMESTAMP;
ALTER TABLE receipts ADD COLUMN IF NOT EXISTS rejection_reason TEXT;
