-- Referral reward redemption tracking (Referrals page + member-addons checkout).
-- Separate from `status` since a referral can sit "successful" for a while
-- before its reward actually gets spent on a purchase.
ALTER TABLE referrals ADD COLUMN IF NOT EXISTS reward_redeemed BOOLEAN NOT NULL DEFAULT FALSE;

-- Singleton settings row backing the Referrals page's Settings tab.
CREATE TABLE IF NOT EXISTS referral_settings (
    id                       BIGINT PRIMARY KEY,
    program_enabled          BOOLEAN NOT NULL DEFAULT TRUE,
    auto_generate_codes      BOOLEAN NOT NULL DEFAULT TRUE,
    email_notifications      BOOLEAN NOT NULL DEFAULT TRUE,
    auto_process_rewards     BOOLEAN NOT NULL DEFAULT FALSE,
    code_prefix              VARCHAR(50) DEFAULT 'GYM',
    link_domain              VARCHAR(255) DEFAULT 'gymbios.app/ref',
    max_rewards_per_member   INTEGER,
    expiry_days              INTEGER DEFAULT 90,
    min_purchase_amount      NUMERIC(10, 2),
    created_at               TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at               TIMESTAMP,
    created_by               VARCHAR(255),
    updated_by               VARCHAR(255)
);

-- Audit trail for "Apply Promotion" on Promotional Access Days promotions —
-- one row per (promotion, member) grant. The unique constraint is what makes
-- applying a promotion idempotent: re-running it never double-grants a member
-- who already received their days.
CREATE TABLE IF NOT EXISTS promotion_access_days_audit (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    promotion_id  BIGINT NOT NULL,
    member_id     BIGINT NOT NULL,
    rule_id       VARCHAR(100),
    applied_days  INTEGER NOT NULL,
    created_at    TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMP,
    created_by    VARCHAR(255),
    updated_by    VARCHAR(255),
    CONSTRAINT uq_promotion_access_days_member UNIQUE (promotion_id, member_id)
);
