-- Referral Reward Redemption System.
-- Extends the existing Referral/ReferralRewardRule program (see
-- V5__referral_and_promotion_extensions.sql) with a full reward lifecycle:
-- rule-driven generation, campaigns, a member reward wallet, coupons, and an
-- audit trail. Nothing here replaces the existing referrals/referral_reward_rules
-- rows or columns — it's purely additive so existing data keeps working.

-- ── Referral: capture what the reward engine needs to validate rule conditions ──
ALTER TABLE referrals ADD COLUMN purchase_amount NUMERIC(10, 2);
ALTER TABLE referrals ADD COLUMN membership_plan_id BIGINT;
ALTER TABLE referrals ADD COLUMN referee_member_id VARCHAR(50);

-- ── Member: reward wallet cached balance (detail ledger is wallet_transactions) ──
ALTER TABLE members ADD COLUMN wallet_balance NUMERIC(12, 2) NOT NULL DEFAULT 0;

-- ── Referral campaigns: optional time-boxed wrapper around one or more rules ──
CREATE TABLE referral_campaigns (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_id   VARCHAR(50) UNIQUE,
    name          VARCHAR(255) NOT NULL,
    description   TEXT,
    start_date    DATE,
    end_date      DATE,
    status        VARCHAR(20) DEFAULT 'scheduled',
    priority      INTEGER DEFAULT 0,
    stackable     BOOLEAN NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMP,
    created_by    VARCHAR(255),
    updated_by    VARCHAR(255)
);

-- ── Reward rule extensions: priority/stacking/campaign/eligibility conditions ──
ALTER TABLE referral_reward_rules ADD COLUMN reward_type VARCHAR(50);
ALTER TABLE referral_reward_rules ADD COLUMN redemption_action VARCHAR(50);
ALTER TABLE referral_reward_rules ADD COLUMN currency VARCHAR(10);
ALTER TABLE referral_reward_rules ADD COLUMN priority INTEGER DEFAULT 0;
ALTER TABLE referral_reward_rules ADD COLUMN stackable BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE referral_reward_rules ADD COLUMN requires_approval BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE referral_reward_rules ADD COLUMN campaign_id BIGINT REFERENCES referral_campaigns(id);
ALTER TABLE referral_reward_rules ADD COLUMN campaign_start_date DATE;
ALTER TABLE referral_reward_rules ADD COLUMN campaign_end_date DATE;
ALTER TABLE referral_reward_rules ADD COLUMN target_membership_plan_id BIGINT;
ALTER TABLE referral_reward_rules ADD COLUMN min_purchase_amount NUMERIC(10, 2);
ALTER TABLE referral_reward_rules ADD COLUMN min_referral_count INTEGER;
ALTER TABLE referral_reward_rules ADD COLUMN max_rewards_per_member INTEGER;

-- ── Referral rewards: one row per (referral, rule, member side) generated reward ──
CREATE TABLE referral_rewards (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reward_code         VARCHAR(50) UNIQUE,
    referral_id         BIGINT NOT NULL REFERENCES referrals(id),
    reward_rule_id      BIGINT NOT NULL REFERENCES referral_reward_rules(id),
    campaign_id         BIGINT,
    campaign_name       VARCHAR(255),
    member_id           VARCHAR(50) NOT NULL,
    member_type         VARCHAR(20) NOT NULL,
    reward_name         VARCHAR(255),
    reward_type         VARCHAR(50) NOT NULL,
    reward_value        NUMERIC(10, 2),
    currency            VARCHAR(10),
    status              VARCHAR(20) NOT NULL,
    redemption_action   VARCHAR(50),
    approval_required   BOOLEAN NOT NULL DEFAULT FALSE,
    approved_by         VARCHAR(255),
    approved_date       TIMESTAMP,
    generated_date      TIMESTAMP,
    expiry_date         DATE,
    claimed_date        TIMESTAMP,
    redeemed_date       TIMESTAMP,
    remarks             TEXT,
    created_at          TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP,
    created_by          VARCHAR(255),
    updated_by          VARCHAR(255),
    -- Prevents the reward engine from ever double-granting the same rule to the
    -- same member side of the same referral, even if it's re-evaluated on retry.
    CONSTRAINT uq_referral_reward_dedup UNIQUE (referral_id, reward_rule_id, member_type)
);

CREATE INDEX idx_referral_rewards_member ON referral_rewards(member_id);
CREATE INDEX idx_referral_rewards_status ON referral_rewards(status);

-- ── Wallet ledger: detail history behind Member.wallet_balance ──
CREATE TABLE wallet_transactions (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id      VARCHAR(50) NOT NULL,
    type           VARCHAR(10) NOT NULL,
    amount         NUMERIC(12, 2) NOT NULL,
    balance_after  NUMERIC(12, 2),
    source_type    VARCHAR(50),
    source_id      BIGINT,
    remarks        TEXT,
    created_at     TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMP,
    created_by     VARCHAR(255),
    updated_by     VARCHAR(255)
);

CREATE INDEX idx_wallet_transactions_member ON wallet_transactions(member_id);

-- ── Coupons: generated lazily for COUPON-type rewards, consumed at checkout ──
CREATE TABLE coupons (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            VARCHAR(50) UNIQUE NOT NULL,
    reward_id       BIGINT NOT NULL REFERENCES referral_rewards(id),
    discount_value  NUMERIC(10, 2),
    discount_unit   VARCHAR(20),
    currency        VARCHAR(10),
    expiry_date     DATE,
    max_uses        INTEGER DEFAULT 1,
    used_count      INTEGER DEFAULT 0,
    status          VARCHAR(20) DEFAULT 'ACTIVE',
    created_at      TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP,
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255)
);

-- ── Reward audit trail: full history per reward (who/what/when/remarks) ──
CREATE TABLE reward_audit_logs (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reward_id      BIGINT NOT NULL REFERENCES referral_rewards(id),
    action         VARCHAR(30) NOT NULL,
    performed_by   VARCHAR(255),
    remarks        TEXT,
    created_at     TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMP,
    created_by     VARCHAR(255),
    updated_by     VARCHAR(255)
);

CREATE INDEX idx_reward_audit_logs_reward ON reward_audit_logs(reward_id);
