-- Staff notes on a member, shown on the Member Analytics page's Notes tab.
-- Previously the page only ever rendered two hardcoded sample notes with no
-- backend at all; this gives it somewhere real to read/write.

CREATE TABLE IF NOT EXISTS member_notes (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id   BIGINT NOT NULL REFERENCES members(id),
    content     TEXT NOT NULL,
    created_at  TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMP,
    created_by  VARCHAR(255),
    updated_by  VARCHAR(255)
);

CREATE INDEX idx_member_notes_member ON member_notes(member_id);
