package com.company.project.entities;

import com.company.project.enums.RedemptionAction;
import com.company.project.enums.RewardMemberType;
import com.company.project.enums.RewardStatus;
import com.company.project.enums.RewardType;
import jakarta.persistence.*;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

// One row per reward instance generated by RewardEngineService for one side
// (referrer or referee) of one successful referral, against one matching rule.
// The unique constraint on (referral_id, reward_rule_id, member_type) is what
// makes reward generation idempotent — re-evaluating the same referral never
// creates a duplicate reward for a rule that already fired.
@Entity
@Table(name = "referral_rewards")
public class ReferralReward extends BaseEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Business ID: RWD-XXXXXXXXXX
    @Column(name = "reward_code", unique = true)
    private String rewardCode;

    @Column(name = "referral_id", nullable = false)
    private Long referralId;

    @Column(name = "reward_rule_id", nullable = false)
    private Long rewardRuleId;

    @Column(name = "campaign_id")
    private Long campaignId;

    @Column(name = "campaign_name")
    private String campaignName;

    // The member this reward belongs to (business id, e.g. MBR-0000000001)
    @Column(name = "member_id", nullable = false)
    private String memberId;

    @Enumerated(EnumType.STRING)
    @Column(name = "member_type", nullable = false)
    private RewardMemberType memberType;

    @Column(name = "reward_name")
    private String rewardName;

    @Enumerated(EnumType.STRING)
    @Column(name = "reward_type", nullable = false)
    private RewardType rewardType;

    @Column(name = "reward_value", precision = 10, scale = 2)
    private BigDecimal rewardValue;

    @Column(name = "currency")
    private String currency;

    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false)
    private RewardStatus status;

    @Enumerated(EnumType.STRING)
    @Column(name = "redemption_action")
    private RedemptionAction redemptionAction;

    @Column(name = "approval_required")
    private Boolean approvalRequired = false;

    @Column(name = "approved_by")
    private String approvedBy;

    @Column(name = "approved_date")
    private LocalDateTime approvedDate;

    @Column(name = "generated_date")
    private LocalDateTime generatedDate;

    @Column(name = "expiry_date")
    private LocalDate expiryDate;

    @Column(name = "claimed_date")
    private LocalDateTime claimedDate;

    @Column(name = "redeemed_date")
    private LocalDateTime redeemedDate;

    @Column(name = "remarks", columnDefinition = "TEXT")
    private String remarks;

    public ReferralReward() {}

    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }

    public String getRewardCode() { return rewardCode; }
    public void setRewardCode(String rewardCode) { this.rewardCode = rewardCode; }

    public Long getReferralId() { return referralId; }
    public void setReferralId(Long referralId) { this.referralId = referralId; }

    public Long getRewardRuleId() { return rewardRuleId; }
    public void setRewardRuleId(Long rewardRuleId) { this.rewardRuleId = rewardRuleId; }

    public Long getCampaignId() { return campaignId; }
    public void setCampaignId(Long campaignId) { this.campaignId = campaignId; }

    public String getCampaignName() { return campaignName; }
    public void setCampaignName(String campaignName) { this.campaignName = campaignName; }

    public String getMemberId() { return memberId; }
    public void setMemberId(String memberId) { this.memberId = memberId; }

    public RewardMemberType getMemberType() { return memberType; }
    public void setMemberType(RewardMemberType memberType) { this.memberType = memberType; }

    public String getRewardName() { return rewardName; }
    public void setRewardName(String rewardName) { this.rewardName = rewardName; }

    public RewardType getRewardType() { return rewardType; }
    public void setRewardType(RewardType rewardType) { this.rewardType = rewardType; }

    public BigDecimal getRewardValue() { return rewardValue; }
    public void setRewardValue(BigDecimal rewardValue) { this.rewardValue = rewardValue; }

    public String getCurrency() { return currency; }
    public void setCurrency(String currency) { this.currency = currency; }

    public RewardStatus getStatus() { return status; }
    public void setStatus(RewardStatus status) { this.status = status; }

    public RedemptionAction getRedemptionAction() { return redemptionAction; }
    public void setRedemptionAction(RedemptionAction redemptionAction) { this.redemptionAction = redemptionAction; }

    public Boolean getApprovalRequired() { return approvalRequired; }
    public void setApprovalRequired(Boolean approvalRequired) { this.approvalRequired = approvalRequired; }

    public String getApprovedBy() { return approvedBy; }
    public void setApprovedBy(String approvedBy) { this.approvedBy = approvedBy; }

    public LocalDateTime getApprovedDate() { return approvedDate; }
    public void setApprovedDate(LocalDateTime approvedDate) { this.approvedDate = approvedDate; }

    public LocalDateTime getGeneratedDate() { return generatedDate; }
    public void setGeneratedDate(LocalDateTime generatedDate) { this.generatedDate = generatedDate; }

    public LocalDate getExpiryDate() { return expiryDate; }
    public void setExpiryDate(LocalDate expiryDate) { this.expiryDate = expiryDate; }

    public LocalDateTime getClaimedDate() { return claimedDate; }
    public void setClaimedDate(LocalDateTime claimedDate) { this.claimedDate = claimedDate; }

    public LocalDateTime getRedeemedDate() { return redeemedDate; }
    public void setRedeemedDate(LocalDateTime redeemedDate) { this.redeemedDate = redeemedDate; }

    public String getRemarks() { return remarks; }
    public void setRemarks(String remarks) { this.remarks = remarks; }
}
